package de.seuhd.campuscoffee.data.persistence.entities

import jakarta.persistence.Column
import jakarta.persistence.Id
import jakarta.persistence.MappedSuperclass
import jakarta.persistence.PostLoad
import jakarta.persistence.PostPersist
import jakarta.persistence.Transient
import org.springframework.data.domain.Persistable
import java.util.UUID

/**
 * Base for the JPA entities whose [UUID] id is assigned by the application rather than generated by the
 * database. Because the id has no `@GeneratedValue`, Spring Data cannot tell a new row from an existing one
 * by a null id, so the entity implements [Persistable]: [isNew] stays true until the row is loaded or
 * persisted (tracked by a transient flag). That lets `repository.save()` insert a freshly built entity
 * without first running a SELECT to check whether it already exists.
 *
 * The id is held in a private field and exposed through `getId()`/`setId()` because a Kotlin property named
 * `id` would compile to the same `getId()` as the [Persistable] override and clash with it. Callers still
 * write `entity.id`, since Kotlin exposes the Java `getId()`/`setId()` pair as a property.
 *
 * The timestamped [Entity] extends this base, and every table's entity extends [Entity].
 */
@MappedSuperclass
abstract class PersistableEntity : Persistable<UUID> {
    @field:Id
    @field:Column(name = "id")
    private var entityId: UUID? = null

    @field:Transient
    private var persisted = false

    override fun getId(): UUID? = entityId

    /**
     * Assigns the entity's id (exposed as the `id` property in Kotlin).
     *
     * @param value the id to assign
     */
    fun setId(value: UUID?) {
        entityId = value
    }

    override fun isNew(): Boolean = !persisted

    /** Flips the new entity flag after the row is loaded or persisted, so [isNew] then returns false. */
    @PostLoad
    @PostPersist
    private fun markPersisted() {
        persisted = true
    }
}
